defaults:
  platforms: [unix]
  for: [scripts, source, binaries]
traits:
  - id: selinux-disabled-config-assignment
    desc: SELinux disabled configuration assignment
    crit: notable
    conf: 0.90
    if:
      type: text
      regex: '(?m)^[ \t]*SELINUX[ \t]*=[ \t]*disabled[ \t]*$'
