defaults:
  for: [class]
  platforms: [ios]
  crit: notable

traits:
  - id: jvm-ios-profile-directory-reference
    desc: JVM iOS configuration-profile path reference
    conf: 0.9
    if:
      type: value
      path: class.strings
      regex: '^/var/mobile/Library/ConfigurationProfiles(/|$)'
