defaults:
  platforms: [unix, windows]
traits:
  - id: makefile-remote-transfer-command
    desc: Build recipe references curl/wget remote URL
    crit: notable
    conf: 0.85
    for: [makefile]
    if:
      type: text
      regex: (curl|wget)\s+.{0,50}(https?|ftp)://
    unless:
      - id: micro-behaviors/ui/help::makefile-echo-download-instruction
