defaults:
  for:
    - pe
    - dll
  platforms:
    - windows
composite_rules:
  - id: mixed-ipv4-endpoint-cluster
    desc: External and private IPv4 endpoints
    crit: suspicious
    conf: 0.94
    all:
      - id: objectives/command-and-control/infrastructure/ip-port::embedded-ipv4-endpoint-pair
      - id: micro-behaviors/communications/ip::private-ipv4-port-10-binary
    any:
      - id: objectives/command-and-control/infrastructure/ip-port::hardcoded-ipv4-port-rdata-list
      - id: micro-behaviors/process/sync/event::create-event
      - id: micro-behaviors/time/schedule/waitable::create-and-set-waitable-timer
      - id: micro-behaviors/os/module/load::dynamic-self-resolution-imports
      - id: metadata/binary/debug::pdb-random-basename
