defaults:
  platforms: [unix]
  for: [javascript, typescript]
composite_rules:
  - id: autostart-config-with-ip-url
    desc: Autostart configuration with external IP URL
    crit: notable
    conf: 0.94
    all:
      - id: micro-behaviors/communications/ip/literal::external-ipv4-url-script
    any:
      - id: micro-behaviors/os/service/launchagent::node-launchd-runatload-plist
      - id: micro-behaviors/os/service/configure::source-systemctl-user-enable
