traits:
- id: rc-local-path-marker
  desc: References rc.local path
  crit: notable
  conf: 0.92
  if:
    type: text
    substr: etc/rc.local
composite_rules: []
defaults:
  platforms:
  - unix
  for:
  - shell
  - scripts
  - binaries
  - elf
