defaults:
  platforms:
    - unix
    - windows
  for: [makefile]
  attack: T1056.001
  mbc: B0015

traits:
  - id: keylog-project-name
    desc: Makefile keylogger project name
    crit: component
    conf: 0.92
    size_max: 4096
    if:
      type: text
      regex: '^PROJECT\s*[:+?]?=\s*ke[ey]log(ger)?[a-z0-9_-]*\b'
      case_insensitive: true

composite_rules:
  - id: windows-bof-keylogger-build
    desc: Windows BOF keylogger build
    crit: hostile
    conf: 0.97
    all:
      - id: keylog-project-name
      - id: metadata/build/make::crtless-dual-arch-bof-build
