defaults:
  platforms: [unix, windows]
traits:
  - id: makefile-echo-download-instruction
    desc: Makefile echoes download instructions
    crit: notable
    conf: 0.9
    for: [makefile]
    if:
      type: text
      regex: '@?echo([^\n]{0,80}\\[\r\n]+\s*|[^\n]{0,80}\b)(curl|wget)\s+.{0,50}https?://'
