# coding: utf-8

"""
    waf

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: common-version

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


class ReasonForListProhibitionOutput(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    swagger_types = {
        'black': 'int',
        'bot': 'int',
        'geo_black': 'int',
        'httpflood': 'int',
        'param_abnormal': 'int',
        'route_abnormal': 'int',
        'sensitive_info': 'int',
        'web_vulnerability': 'int'
    }

    attribute_map = {
        'black': 'black',
        'bot': 'bot',
        'geo_black': 'geo_black',
        'httpflood': 'httpflood',
        'param_abnormal': 'param_abnormal',
        'route_abnormal': 'route_abnormal',
        'sensitive_info': 'sensitive_info',
        'web_vulnerability': 'web_vulnerability'
    }

    def __init__(self, black=None, bot=None, geo_black=None, httpflood=None,
                 param_abnormal=None, route_abnormal=None,
                 sensitive_info=None, web_vulnerability=None):
        """ReasonForListProhibitionOutput - a model defined in Swagger"""  # noqa: E501
        self.httpflood = httpflood
