defaults:
  platforms:
  - unix
  - windows
  for: [makefile]
  attack: T1027

composite_rules:
  - id: crtless-stripped-cross-compile
    desc: Stripped CRT-less MinGW cross-build
    crit: suspicious
    conf: 0.93
    all:
      - id: metadata/build/make::makefile-basename
      - id: metadata/build/make::dual-arch-mingw-cross-compile
      - id: metadata/build/make::strip-all-symbols-flag
      - id: metadata/build/make::no-ntdll-crt-flag
  - id: keylogger-crtless-stripped-build
    desc: Keylogger strips CRT from dual-arch build
    crit: hostile
    conf: 0.97
    all:
      - id: objectives/collection/keylog/capture::keylog-project-name
      - id: crtless-stripped-cross-compile
