defaults:
  platforms:
  - unix
  - windows
  for: [makefile]
  attack: T1027

composite_rules:
  - id: hidden-symbol-build
    desc: Makefile hides symbols and debug info
    crit: suspicious
    conf: 0.92
    all:
      - id: metadata/build/make::makefile-basename
      - id: metadata/build/make::hidden-visibility-flag
      - id: metadata/build/make::objcopy-strip-debug-command
    any:
      - id: metadata/build/make::no-debug-flag
      - id: metadata/build/make::no-stack-protector-flag
  - id: crtless-stripped-cross-compile
    desc: Stripped CRT-less MinGW cross-build
    crit: suspicious
    conf: 0.93
    all:
      - id: metadata/build/make::makefile-basename
      - id: metadata/build/make::dual-arch-mingw-cross-compile
      - id: metadata/build/make::strip-all-symbols-flag
      - id: metadata/build/make::no-ntdll-crt-flag
