defaults:
  platforms:
  - unix
  - windows
  for: [makefile]
  attack: T1027

composite_rules:
  - id: hidden-symbol-build
    desc: Makefile hides symbols and debug info
    crit: suspicious
    conf: 0.92
    all:
      - id: metadata/build/make::makefile-basename
      - id: metadata/build/make::hidden-visibility-flag
      - id: metadata/build/make::objcopy-strip-debug-command
    any:
      - id: metadata/build/make::no-debug-flag
      - id: metadata/build/make::no-stack-protector-flag

